# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.14.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
#dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
X[:,2]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [10]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
y_test.shape

(2000,)

Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [16]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
X_train.shape

(8000, 12)

## Part 2 - Building the ANN

### Initializing the ANN

In [22]:
ann = tf.keras.models.Sequential()
type(ann)

keras.src.engine.sequential.Sequential

### Adding the input layer and the first hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [27]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 479us/step - loss: 0.5538 - accuracy: 0.7846
Epoch 2/100
250/250 [==============================] - 0s 435us/step - loss: 0.4554 - accuracy: 0.8081
Epoch 3/100
250/250 [==============================] - 0s 442us/step - loss: 0.4306 - accuracy: 0.8152
Epoch 4/100
250/250 [==============================] - 0s 448us/step - loss: 0.4200 - accuracy: 0.8176
Epoch 5/100
250/250 [==============================] - 0s 478us/step - loss: 0.4128 - accuracy: 0.8261
Epoch 6/100
250/250 [==============================] - 0s 488us/step - loss: 0.4069 - accuracy: 0.8271
Epoch 7/100
250/250 [==============================] - 0s 468us/step - loss: 0.4022 - accuracy: 0.8286
Epoch 8/100
250/250 [==============================] - 0s 435us/step - loss: 0.3983 - accuracy: 0.8306
Epoch 9/100
250/250 [==============================] - 0s 443us/step - loss: 0.3946 - accuracy: 0.8305
Epoch 10/100
250/250 [==============================] - 0s 450us/step - l

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [43]:
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 390us/step


In [29]:
y_pred

array([[0.21452235],
       [0.24088405],
       [0.1327343 ],
       ...,
       [0.11566151],
       [0.20636252],
       [0.22279981]], dtype=float32)

In [44]:
y_pred = (y_pred > 0.5)

In [32]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # Basis for matrix

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1514   81]
 [ 193  212]]


In [46]:
accuracy_score(y_test, y_pred)

0.863

Use our ANN model to predict if the customer with the following informations will leave the bank:
 
Geography: France
 
Credit Score: 600
 
Gender: Male
 
Age: 40 years old
 
Tenure: 3 years
 
Balance: $ 60000
 
Number of Products: 2
 
Does this customer have a credit card? Yes
 
Is this customer an Active Member: Yes
 
Estimated Salary: $ 50000
 
So, should we say goodbye to that customer?

In [ ]:
# Insert values, remember the one-hot encoding of Geography
# The one hot encoded columns are placed furthest to the left, 
# and the Geography column disappears. Female / Male is 
# encoded to 0 / 1

In [47]:
evaluationTarget = sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])
ann.predict(evaluationTarget)

1/1 [==============================] - 0s 10ms/step


array([[0.02661874]], dtype=float32)

In [48]:
ann.predict(evaluationTarget) > 0.5

1/1 [==============================] - 0s 8ms/step


array([[False]])